import './globals.css'
import ReduxProvider from './store/provider'
export const metadata = {
  title: 'instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
